name: 'Setup Rust Cache'
description: 'Cache Cargo registry and build artifacts'
inputs:
  cache-key-prefix:
    description: 'Prefix for the cache key (e.g., "rust-cargo" or "elixir-cargo")'
    required: false
    default: 'rust-cargo'
runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ inputs.cache-key-prefix }}-${{ hashFiles('**/Cargo.lock') }}
